### ISSUE TITLE
dwarfii_api__WEBPACK_IMPORTED_MODULE_2

### ISSUE THREAD

**Issue by Silky-Thrower** [DwarfTelescopeUsers/dwarfii-stellarium-goto#6]
Hello Steve,

When importing the new version I cannot connect to the Dwarf. 
Is there something I'm overlooking?
![problem connecting](https://github.com/DwarfTelescopeUsers/dwarfii-stellarium-goto/assets/154828328/95798bde-d2f5-4e54-80cc-3eb72af265b0)

**Comment by acocalypso** [comment]
Same here using node 20

**Comment by Silky-Thrower** [comment]
The prebuild version with on localhost:8000 works normal
But only in slave mode... why do i have to be connected with my phone ?
![problem connecting-prebuild](https://github.com/DwarfTelescopeUsers/dwarfii-stellarium-goto/assets/154828328/b2f70aea-3219-4dd1-89d0-b536801def22)

**Comment by acocalypso** [comment]
can be closed already fixed in apiv2
